import Link from 'next/link';

export default function Whitepaper() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pb-32 pt-20 relative z-10">
      
      {/* Background Ambience */}
      <div className="fixed top-0 left-0 w-full h-full pointer-events-none overflow-hidden -z-10">
        <div className="absolute top-1/4 right-0 w-[400px] h-[400px] bg-red-600/5 rounded-full blur-[150px]" />
        <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.01)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.01)_1px,transparent_1px)] bg-[size:3rem_3rem] [mask-image:radial-gradient(ellipse_80%_80%_at_50%_0%,#000_20%,transparent_100%)]"></div>
      </div>

      {/* Título Masivo */}
      <div className="mb-16 border-b border-zinc-800/80 pb-12">
        <Link href="/docs" className="text-zinc-500 hover:text-white transition-colors text-[10px] font-black uppercase tracking-[0.2em] mb-8 inline-block flex items-center gap-2">
          <span>&larr;</span> Back to Docs
        </Link>
        <h1 className="text-4xl md:text-6xl font-black tracking-tighter uppercase text-transparent bg-clip-text bg-gradient-to-br from-white via-zinc-300 to-zinc-600 mt-4 leading-[1.1]">
          JOINUS! <br/>
          THE FINANCIAL <span className="text-red-500 drop-shadow-[0_0_15px_rgba(239,68,68,0.5)]">REBELLION</span>
        </h1>
        <p className="text-zinc-500 mt-6 tracking-[0.3em] uppercase text-xs font-bold border-l-2 border-red-500 pl-4">
          Official Whitepaper v1.0
        </p>
      </div>

      {/* Contenido / Índice */}
      <div className="grid grid-cols-1 md:grid-cols-12 gap-12">
        
        {/* Sidebar Index */}
        <div className="md:col-span-4">
          <div className="sticky top-28 bg-[#0a0a0a]/80 backdrop-blur-md border border-zinc-800/80 rounded-2xl p-6 shadow-2xl">
            <h3 className="text-white text-[10px] font-black uppercase tracking-[0.3em] mb-6 pb-4 border-b border-zinc-800/50">Table of Contents</h3>
            <ul className="space-y-4 text-xs font-bold tracking-widest uppercase">
              <li>
                <a href="#manifesto" className="text-zinc-400 hover:text-red-400 transition-colors flex items-center gap-2">
                  <span className="text-zinc-700">01.</span> Manifesto
                </a>
              </li>
              <li>
                <a href="#economics" className="text-zinc-400 hover:text-red-400 transition-colors flex items-center gap-2">
                  <span className="text-zinc-700">02.</span> Asymptotic Economics
                </a>
              </li>
              <li>
                <a href="#governance" className="text-zinc-400 hover:text-red-400 transition-colors flex items-center gap-2">
                  <span className="text-zinc-700">03.</span> ZK Governance
                </a>
              </li>
              <li>
                <a href="#arena" className="text-zinc-400 hover:text-red-400 transition-colors flex items-center gap-2">
                  <span className="text-zinc-700">04.</span> The Arena & Real Yield
                </a>
              </li>
            </ul>
          </div>
        </div>

        {/* Content Body */}
        <div className="md:col-span-8 space-y-16">
          <section id="manifesto" className="scroll-mt-32">
            <h2 className="text-2xl font-black text-white uppercase tracking-widest mb-6 flex items-center gap-4">
              <span className="text-red-500 text-sm">01.</span> Manifesto
            </h2>
            <div className="prose prose-invert prose-zinc max-w-none text-zinc-400 leading-relaxed font-medium">
              <p>The legacy financial system is structurally designed to extract value from the user. We are building the opposite: a sovereign economic engine where all the value generated by its products is asymptotically routed back to the community.</p>
              <p>JOINUS is not just a protocol, it is the financial rebellion.</p>
            </div>
          </section>

          <section id="economics" className="scroll-mt-32">
            <h2 className="text-2xl font-black text-white uppercase tracking-widest mb-6 flex items-center gap-4">
              <span className="text-red-500 text-sm">02.</span> Asymptotic Economics
            </h2>
            <div className="prose prose-invert prose-zinc max-w-none text-zinc-400 leading-relaxed font-medium">
              <p>Content goes here...</p>
            </div>
          </section>
          
          <section id="governance" className="scroll-mt-32">
            <h2 className="text-2xl font-black text-white uppercase tracking-widest mb-6 flex items-center gap-4">
              <span className="text-red-500 text-sm">03.</span> ZK Governance
            </h2>
            <div className="prose prose-invert prose-zinc max-w-none text-zinc-400 leading-relaxed font-medium">
              <p>Content goes here...</p>
            </div>
          </section>

          <section id="arena" className="scroll-mt-32">
            <h2 className="text-2xl font-black text-white uppercase tracking-widest mb-6 flex items-center gap-4">
              <span className="text-red-500 text-sm">04.</span> The Arena & Real Yield
            </h2>
            <div className="prose prose-invert prose-zinc max-w-none text-zinc-400 leading-relaxed font-medium">
              <p>Content goes here...</p>
            </div>
          </section>
        </div>

      </div>
    </div>
  );
}
